# Generated by Django 6.0.4 on 2026-05-02 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to='inventory_images/'),
        ),
    ]
