# Generated by Django 6.0.4 on 2026-05-05 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_inventory_status_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='state',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('owenr', 'Owner'), ('customer', 'Customer'), ('employee', 'Employee (Future Implementation)')], max_length=20),
        ),
    ]
