# Generated by Django 6.0.4 on 2026-05-06 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_owner_state_profile_otp_profile_otp_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='sub_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='inventory',
            name='subcategory',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
