# Generated by Django 6.0.4 on 2026-05-06 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_inventory_sub_type_inventory_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='return_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
