# Generated by Django 6.0.4 on 2026-05-06 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_booking_district_booking_item_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='event_date',
        ),
        migrations.AddField(
            model_name='booking',
            name='end_date',
            field=models.DateField(default='2026-05-06'),
        ),
        migrations.AddField(
            model_name='booking',
            name='start_date',
            field=models.DateField(default='2026-05-06'),
        ),
        migrations.AddField(
            model_name='booking',
            name='venue',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
